version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/auth-service"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "maven"
  - package-ecosystem: "maven"
    directory: "/catalog-service"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "maven"
  - package-ecosystem: "maven"
    directory: "/inventory-service"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "maven"
  - package-ecosystem: "maven"
    directory: "/purchase-service"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "maven"
  - package-ecosystem: "maven"
    directory: "/sales-service"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "maven"
  - package-ecosystem: "maven"
    directory: "/report-service"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "maven"
  - package-ecosystem: "maven"
    directory: "/api-gateway"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "maven"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
