services:

  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - axiserp-network

  catalog-service:
    build: ./catalog-service
    container_name: catalog-service
    restart: unless-stopped
    ports:
      - "8082:8082"
    env_file:
      - .env
    networks:
      - axiserp-network

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    restart: unless-stopped
    ports:
      - "8083:8083"
    env_file:
      - .env
    networks:
      - axiserp-network

  purchase-service:
    build: ./purchase-service
    container_name: purchase-service
    restart: unless-stopped
    ports:
      - "8086:8086"
    env_file:
      - .env
    networks:
      - axiserp-network

  sales-service:
    build: ./sales-service
    container_name: sales-service
    restart: unless-stopped
    ports:
      - "8084:8084"
    env_file:
      - .env
    networks:
      - axiserp-network

  report-service:
    build: ./report-service
    container_name: report-service
    restart: unless-stopped
    ports:
      - "8085:8085"
    env_file:
      - .env
    networks:
      - axiserp-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - catalog-service
      - inventory-service
      - purchase-service
      - sales-service
      - report-service
    networks:
      - axiserp-network

networks:
  axiserp-network: