# NOTA: projectKey y organization se definen en ci-template.yml con -D flags
# Este archivo es solo para referencia local
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/test/**/*,**/target/**
sonar.java.source=21
sonar.scm.provider=git
