spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - http://localhost:*
              - https://*.vercel.app
              - https://frontend-axis-erp.vercel.app
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowed-headers:
              - '*'
            allow-credentials: true
            max-age: 3600

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.web.reactive: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info

server:
  port: 8080
  error:
    include-exception: false
    include-message: never
    include-stacktrace: never
