spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.web.reactive: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info

server:
  port: 8080
  error:
    include-exception: false
    include-message: never
    include-stacktrace: never
