trigger:
  branches:
    include:
      - master
  paths:
    include:
      - inventory-service/**

jobs:
  - template: template.yml
    parameters:
      service: inventory-service
      port: 8083
