name: CD - Deploy to Azure

on:
  push:
    branches: [master]
    paths:
      - auth-service/**
      - catalog-service/**
      - inventory-service/**
      - sales-service/**
      - purchase-service/**
      - report-service/**
      - api-gateway/**
  workflow_dispatch:

env:
  ACR_SERVER: axiserp.azurecr.io

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, catalog-service, inventory-service, sales-service, purchase-service, report-service, api-gateway]
    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        run: |
          az login -u "${{ secrets.AZURE_USER }}" -p "${{ secrets.AZURE_PASS }}" --allow-no-subscriptions
          az account set -s "48482985-813d-4a7c-a283-350c1d90799c"

      - name: Login to ACR
        run: az acr login --name axiserp

      - name: Build & Push Docker image
        run: |
          docker build --platform linux/amd64 \
            -t $ACR_SERVER/${{ matrix.service }}:latest \
            -f ${{ matrix.service }}/Dockerfile \
            ${{ matrix.service }}
          docker push $ACR_SERVER/${{ matrix.service }}:latest

      - name: Update Container App
        run: |
          az containerapp update \
            --name ${{ matrix.service }} \
            --resource-group axiserp-prod \
            --image $ACR_SERVER/${{ matrix.service }}:latest \
            --min-replicas 1 --max-replicas 10
