name: CI - Auth Service

on:
  push:
    branches: [master]
    paths:
      - auth-service/**
  pull_request:
    branches: [master]
    paths:
      - auth-service/**
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/template-ci.yml
    with:
      service: auth-service
      port: 8081
    secrets: inherit
