name: CI - Auth Service

on:
  push:
    paths:
      - 'auth-service/**'
      - '.github/workflows/ci-auth.yml'
      - '.github/workflows/ci-template.yml'
  pull_request:
    paths:
      - 'auth-service/**'

concurrency:
  group: ci-auth-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      service: auth-service
