name: CI - API Gateway
on:
  push:
    branches: [master]
    paths: [api-gateway/**]
  pull_request:
    branches: [master]
    paths: [api-gateway/**]
  workflow_dispatch:
jobs:
  ci:
    uses: ./.github/workflows/template-ci.yml
    with:
      service: api-gateway
    secrets: inherit
