name: CI - Inventory Service

on:
  push:
    paths:
      - 'inventory-service/**'
      - '.github/workflows/ci-inventory.yml'
      - '.github/workflows/ci-template.yml'
  pull_request:
    paths:
      - 'inventory-service/**'
      - '.github/workflows/ci-inventory.yml'
      - '.github/workflows/ci-template.yml'

permissions:
  contents: read
  actions: write

concurrency:
  group: ci-inventory-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      service: inventory-service
      build-docker: false
