name: CI - Report Service

on:
  push:
    paths:
      - 'report-service/**'
      - '.github/workflows/ci-report.yml'
      - '.github/workflows/ci-template.yml'
  pull_request:
    paths:
      - 'report-service/**'

permissions:
  contents: read
  security-events: write

concurrency:
  group: ci-report-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      service: report-service
