name: CI - Sales Service

on:
  push:
    paths:
      - 'sales-service/**'
      - '.github/workflows/ci-sales.yml'
      - '.github/workflows/ci-template.yml'
  pull_request:
    paths:
      - 'sales-service/**'
      - '.github/workflows/ci-sales.yml'
      - '.github/workflows/ci-template.yml'

concurrency:
  group: ci-sales-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      service: sales-service
      build-docker: false
      run-trivy: true
