name: CI - Sales Service

on:
  push:
    paths:
      - 'sales-service/**'
      - '.github/workflows/ci-sales.yml'
      - '.github/workflows/ci-template.yml'
  pull_request:
    paths:
      - 'sales-service/**'

jobs:
  ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      service: sales-service
